from __future__ import annotations

from pathlib import Path

from shared.io.markdown_writer import write_markdown
from shared.io.json_store import write_json
from knowledge_studio.vision.schemas.room import RoomDNA


def render(dna: RoomDNA, output_dir: Path, filename: str = "VENHO_ROOM_DNA") -> dict[str, Path]:
    """Render RoomDNA to .md + .json files. Returns paths."""
    output_dir.mkdir(parents=True, exist_ok=True)
    md_path = output_dir / f"{filename}.md"
    json_path = output_dir / f"{filename}.json"

    write_markdown(md_path, _build_markdown(dna))
    write_json(json_path, dna.model_dump())

    return {"md": md_path, "json": json_path}


def _confidence_badge(confidence: float) -> str:
    if confidence >= 0.8:
        return "🟢"
    if confidence >= 0.5:
        return "🟡"
    return "🔴"


def _build_markdown(dna: RoomDNA) -> list[str]:
    lines: list[str] = []

    # Header
    lines += [
        f"# VENHO ROOM DNA",
        f"",
        f"**Subject:** {dna.subject}  ",
        f"**DNA Version:** {dna.dna_version}  ",
        f"**Generated:** {dna.generated_at}  ",
        f"**Schema Version:** {dna.schema_version}  ",
        f"**Prompt Version:** {dna.prompt_version}  ",
        f"**Source Images:** {len(dna.source_images)}  ",
        f"",
        "---",
        "",
    ]

    # META
    lines += [
        "## META",
        "",
        f"- Subject: `{dna.subject}`",
        f"- DNA version: `{dna.dna_version}`",
        f"- Total source images: `{dna.evidence.total_images}`",
        f"- Generated at: `{dna.generated_at}`",
        "",
    ]

    # INVARIANT
    lines += ["## INVARIANT", "", "_Features that are permanent and must appear in every AI generation._", ""]
    if dna.invariant:
        for feat in dna.invariant:
            badge = _confidence_badge(feat.confidence)
            lines.append(
                f"- {badge} **{feat.key}** ({feat.category}) — {feat.value}"
                f" _(evidence: {feat.evidence_count}, confidence: {feat.confidence:.2f})_"
            )
    else:
        lines.append("_No invariant features identified._")
    lines.append("")

    # VARIABLE
    lines += ["## VARIABLE", "", "_Features that may vary between images._", ""]
    if dna.variable:
        for feat in dna.variable:
            badge = _confidence_badge(feat.confidence)
            lines.append(
                f"- {badge} **{feat.key}** ({feat.category}) — {feat.value}"
            )
    else:
        lines.append("_No variable features identified._")
    lines.append("")

    # FORBIDDEN
    lines += ["## FORBIDDEN", "", "_Negative rules — what this room is NOT._", ""]
    for rule in dna.forbidden:
        lines.append(f"- ❌ {rule}")
    if not dna.forbidden:
        lines.append("_No forbidden rules identified._")
    lines.append("")

    # EVIDENCE
    lines += ["## EVIDENCE", ""]
    lines.append(f"- Total images analyzed: **{dna.evidence.total_images}**")
    if dna.evidence.weak_features:
        lines.append(f"- Weak features (need more photos): {', '.join(f'`{f}`' for f in dna.evidence.weak_features)}")
    else:
        lines.append("- Weak features: _none — all features well-evidenced_")
    lines += ["", "---", f"_Generated by VENHO AI Studio v{dna.dna_version}_"]

    return lines
